- src/controls.js
- src/viewer.js
- webpack.config.js
This PR cleans up the viewer blendshape support, specifically:
- clean up morph referencing/indexing by removing unnecessary morphMap
- name morph groups nicely (instead of using mesh index)
- update morph weight sliders when playing animations
> Morphs update

- src/index.ejs
- webpack.config.js
This PR updates the path for the playcanvas logo image in the index.html file when building using `npm run build:server`.
> Fix playcanvas logo for server builds

- webpack.config.js
This PR sets the webpack source map config to two different presets based on the build type:
Local development (`npm run watch`):
```
eval-source-map - Each module is executed with eval() and a SourceMap is added as a DataUrl to the eval(). Initially it is slow, but it provides fast rebuild speed and yields real files. Line numbers are correctly mapped since it gets mapped to the original code. It yields the best quality SourceMaps for development.
```
Dev server & prod server (`npm run build:server`):
```
source-map - A full SourceMap is emitted as a separate file. It adds a reference comment to the bundle so development tools know where to find it.
``` 
I confirm I have signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6f …
> Update webpacks sourcemap config

- .gitignore
- src/lib/hdr-texture.js
Disable HDR format mipmaps because RGBE pixels can't be filtered (and so the the auto-generated versions are wrong).
> Fix HDR issue

- package.json
- src/controls.js
- src/helpers.js
- src/index.js
- src/viewer.js
- webpack.config.js
Fixes #41 
Allows the playcanvas-viewer to be built with a local version of the engine. You can supply the engine path as follows:
`ENGINE_PATH=../engine/build/playcanvas.js npm run build:watch`
> Support local builds of the playcanvas engine

- src/controls.ts
- src/cta.ts
- src/index.ts
- src/viewer.ts
The library files don't have any typescript definitions, so they're throwing errors when picked up by the typescript compiler. This ensures they're always ignored.
> Server build typescript error fix

- src/index.ejs
- static/manifest.json
Adds an app manifest for installing the viewer to a device's home screen.
Fixes #65
> Add app manifest

- src/controls.tsx
- src/index.tsx
- src/viewer.ts
Fixes #76
Adds tonemapping selection:
Default is ACES.
> Expose tonemapping selection

- package-lock.json
- package.json
- src/controls.tsx
- src/fonts.css
- webpack.config.js
Fixes #81 
This PR bumps the version of PCUI to 1.1.5. This version of PCUI no longer includes fonts, so they've been added back in here. It also has a change in the way SliderInputs are declared. Finally, react is no longer imported by default into PCUI components so it's included via webpack config here.
> PCUI v1.1.5

- src/viewer.ts
instead of depending on defaults
> Implicit code to specify 2d texture uses equirect projection instead

- package-lock.json
- package.json
- src/debug.ts
- src/graph.ts
- src/index.tsx
- src/viewer.ts
This PR updates the PlayCanvas NPM package from 1.39.0 to 1.39.4. This requires the app to explicitly import `pc` as follows:
```typescript
import * as pc from 'playcanvas';
```
> Update PlayCanvas to 1.39.4

- package-lock.json
- src/controls.tsx
- src/index.tsx
- src/viewer.ts
Animation tracks are now displayed in a dropdown rather than individual buttons.
The dropdown has an extra option 'All tracks' which will play all animation tracks sequentially.
Different animation controls will now display depending on whether playing a single track or all tracks:
The controls for single tracks includes a timeline slider to allow users to move through an animation tracks timeline.
> Animation Timeline

- src/debug.ts
- src/index.tsx
- src/viewer.ts
The viewer sourcebase has 58 occurrences of `ts-ignore`. This PR eliminates 22 of them leaving just 36 more to fix. 
This PR also:
* Updates some PlayCanvas function calls to conform with the currently supported API.
* Updates some function expressions  to be arrow functions.
* Fixes some spelling mistakes.
> Eliminate some occurrences of ts-ignore

- package-lock.json
- package.json
- rollup.config.js
- src/index.mustache
- tsconfig.json
Small fixes for the server build of the viewer including to the style tag and the public path replacement.
Also updates the typescript plugin from `rollup-plugin-typescript` to `rollup-plugin-typescript2`. The former is designed to produce slightly faster build times but omits any type error logging in the console.
> Rollup build fix

- src/controls.tsx
- src/errors.tsx
- src/load-ui.tsx
- src/types.ts
- src/viewer.ts
The viewer source was declaring its own type declaration for `Observer` despite the typings being present in the `@playcanvas/observer` NPM package.
> Get `Observer` type from NPM package

- src/style.css
Fixes an issue with the display of error messages in the model viewer.
Before:
After:
Fixes #153 
> Fix the error box layout

- src/controls.tsx
The useObserverState function in the controls file was registering multiple observer set functions for the same action. This meant as the UI reloaded, an increasing amount of events would fire, slowing down interactions with the page.
Fixes #120 
> Fix the useObserverState function

- src/multiframe.ts
- src/read-depth.ts
- src/viewer.ts
Multiframe rendering and depth reading logic was based on backbuffer dimensions instead of render target dimensions.
This PR fixes that and also adds alternative sampling layouts. Different sampling schemes can now be tested in the developer window using, for example:
```
viewer.setSamples(5, false, 2, 0);
```
> Multiframe update

- src/style.css
- src/viewer.ts
Fixes an issue where the animation timeline slider would not update it's value based on the playback of the current animation.
> Animation player fix

- src/index.tsx
- src/types.ts
- src/ui/index.tsx
- src/ui/left-panel/index.tsx
- src/ui/left-panel/morph-target-panel.tsx
- src/viewer.ts
Refactors the creation of morph target data in the viewer so it no longer depends on morph instances containing a reference to their mesh instance.
> Morph targets fix

- package-lock.json
- package.json
- src/ui/index.tsx
- src/ui/left-panel/morph-target-panel.tsx
- src/viewer.ts
To prioritise the performance of the application when animating assets with large amounts of morph targets, the MorphTargetPanel no longer subscribes to animation updates, however morph target sliders can still update the viewer application like before.
> MorphTargetPanel animation update change

- src/app.ts
- tsconfig.json
Also remove the hard-coded tsconfig since rollup config handles this already (and supports local package override https://github.com/playcanvas/model-viewer/blob/main/rollup.config.mjs#L34).
> Add binary handler so loading gltf files work again

- src/viewer.ts
Viewer doesn't need clustered lighting and startup is impacted on windows.
> Disable clustered lighting

- src/ui/load-controls.tsx
This is a followup from #207.
Use URL class instead of custom regex to check validity of text as a URL.
Also, only specify a default filename extension if one isn't already present.
> Use URL to check validity of url

- src/style.scss
This change brings the fonts in Safari and Firefox inline with Chrome.
> Set font weight

- src/viewer.ts
In a recent [engine PR](https://github.com/playcanvas/engine/pull/5291) we changed the gltf loading flow to be asynchronous in order to speed up load times.
As a result the gltf callbacks are now passing promises instead of concrete data.
This PR fixes model-viewer to handle the API change (which must be documented on the engine).
> Meshopt loading fix

- src/viewer.ts
Sometimes glb and gltf files are served without extension. With this PR these can now be loaded in the viewer.
> Load extension-less files as models

- package-lock.json
- package.json
- rollup.config.mjs
No longer maintained and conflicts with typescript plugin.  It does not appear to contribute to sourcemaps in development builds.
Fixes warnings during npm install.
> chore: remove rollup-plugin-sourcemaps

- package-lock.json
- package.json
- src/shadow-catcher.ts
- src/style.scss
Updates project to engine 1.65.3 and adjustments for PCUI 4.1.1
- updates dependency to "playcanvas": "^1.65.3",
- use new naming standard in shadow catcher shader fragment
- increase left panel default size so scroll bar does not show by default with the thicker fonts.
Fixes #229
> chore: update to engine ^1.65.3

- src/sort-worker.ts
- src/splat-resource.ts
This PR updates splat rendering as follows:
- sorting is now 3-4x faster (but still happens on CPU)
- move calculating covarience A & B to the vertex shader so we can support model matrix in future
- also aligns vertex data for rendering & debug modes
> Splat updates

- src/sort-worker.ts
- src/splat-resource.ts
This PR:
- Fixes a bug where splats where incorrectly sized for the viewport
- Adds optional debug bound rendering
> Splat fix and debug rendering

- package-lock.json
- package.json
- src/index.tsx
- src/viewer.ts
This PR:
- fixes handling of argument camera position, which wasn't being used correctly with splats
- added similar `cameraFocus` param
> Handle camera position and focus

- src/splat/sort-manager.ts
- src/splat/splat-data.ts
- src/splat/splat-material.ts
- src/splat/splat-resource.ts
- src/splat/splat.ts
This PR address a few issues with splat sorting:
- render splats orientation correctly with non-identity model matrix
- sort splats correctly with non-identity model matrix
Also:
- added function to transform `SplatData`, used to orientate the scene at load time
- split out worker code with view to supporting multiple splats in future
> Splat sorting fixes

- src/splat/sort-manager.ts
Before sorting splats in the worker we must calculate the splat distance min and max so we can pack the normalised distances into an integer array for sorting.
Instead of running through all splats each time to calculate min and max, we use the splat bounding box instead, saving on sort time.
> Splat sort update

- package-lock.json
- package.json
- src/orbit-camera.ts
- src/splat/splat.ts
- src/viewer.ts
This PR updates the viewer as follows:
- initialise splat order buffer so first frame is sensible
- clamp orbit camera min/max
- calculate scene bounds in first frame
> Splat and camera updates

- package-lock.json
- package.json
- src/viewer.ts
This PR fixes https://forum.playcanvas.com/t/model-viewer-4-7-0/33617.
The scene bound is only valid after rendering the scene once when skinned meshes are loaded.
In this PR we re-calculate the scene bounds and focus the camera again after the first render.
> Fix camera focus of skinned meshes

- src/splat/sort-manager.ts
- in the final pass of the radix sort, do not update temp array followed by copy to target array, but generate target array directly as temp array is no longer needed to be sorted. 
- This saves about 10% of worker time.
> Small optimization of splat sorting

- src/splat/sort-manager.ts
- The sorting was memory access limited, and so this is optimization to limit memory access. Two pass radix sort has been replaced by a single pass (so a counting sort) with larger number of buckets (2^16 vs 2^8)
- Counting sort has been inline into the main loop, to avoid separate loops over splats to generate distances and then to copy sorted output out - this are now done as part of preparing keys / sorting
- removed Big64 array in preference of two 32bit arrays to simplify indexing
- now that it is single pass sorting, got rid of the large temp array as the sorting takes place directly to the output array
Train model performance improvement:
before: 16ms
now: 5ms
> Optimized splat sorting to make it 3x faster

- src/ui/components/index.tsx
- src/ui/errors.tsx
- src/ui/index.tsx
- src/ui/left-panel/index.tsx
- src/ui/left-panel/morph-target-panel.tsx
- src/ui/load-controls.tsx
- src/ui/popup-panel/animation-controls.tsx
- src/ui/popup-panel/index.tsx
- src/ui/popup-panel/panels.tsx
- src/ui/selected-node.tsx
- tsconfig.json
This PR updates the Model Viewer React code to import PCUI in the way recommended by the [PCUI docs](https://playcanvas.github.io/pcui/react/), namely:
```
import { TextInput } from '@playcanvas/pcui/react';
```
This eliminates a large number of Intellisense errors in the project across all the `.tsx` files. For example, errors like these:
> Set import paths correctly for PCUI React

- src/style.scss
Fixes #281 
Correctly sets styling to wrap animation controls on smallers screens
> Animation controls view on smaller screens

- src/ui/popup-panel/index.tsx
- tsconfig.json
Fix Intellisense errors related to PCUI React components. Also remove an unused import.
> Fix path to PCUI in tsconfig.json

- package-lock.json
- package.json
- src/debug-lines.ts
- src/index.mustache
- src/index.tsx
- src/multiframe.ts
- src/projective-skybox.ts
- src/types.ts
- src/ui/left-panel/index.tsx
- static/manifest.json
* update dependencies, including latest engine
* update manifest to get pwa working
> Update to engine v1.71

- src/viewer.ts
> Decode external uri during search

- src/style.scss
Scrollbar styling was implemented in PCUI in 4.4.0: https://github.com/playcanvas/pcui/releases/tag/v4.4.0
This means that Model Viewer no longer needs to specify its own scrollbar styling so it is removed in this PR.
> Use PCUI for scrollbar styling
