src/viewer.js

[FIX] Force render on window resize

---

index.html
src/controls.js
src/viewer.js
style.css

Update the viewer ui using the PlayCanvas ui framework

---

src/index.js

Just to make it simpler to understand what's going on
Fixes #

Export viewer / Allow testing around in devtools

---

src/controls.js
src/viewer.js

Migrate viewer to the new Anim component.
The benefits are:
- ability to play multiple animations simultaneously
- state graph system allows us to do more fancy stuff in future
- code demonstrate PlayCanvas animation state-of-the-art
UI changes:
- shift+click animation buttons to play the animation on top of what's already playing
- increase maximum play speed to 4
- play button now plays all animations
These changes should allow us to pass https://cx20.github.io/gltf-test/examples/playcanvas/index.html?category=tutorialModels&model=InterpolationTest&scale=0.2&type=glTF

Use new anim component

---

src/viewer.js

Add option of loading models and textures using url parameter 'load' or 'assetUrl'.

Add load param

---

src/index.ejs

Added some meta tags to create a nicer listing on Google.

Add meta tags for Google listing

---

src/viewer.js

Fixes #29
This PR makes the following changes:
- removes the confusing shiny ball
- fix the issue that loading animations from a second file caused the first to stop working
- handle url load param slightly differently
- small cubemap handling fixes

Remove shiny ball, anim fix

---

src/helpers.js
src/index.ejs
webpack.config.js

This is a QOL pr for static asset management when hosting the viewer on a server.

Copy static files into their own folder in the dist folder

---

src/helpers.js
src/index.ejs
webpack.config.js

Further adjustments for server config.

Move index.html out of the dist/static folder

---

webpack.config.js

update the static files dist folder

---

package.json

Update the public path for the server webpack config

---

package-lock.json
package.json
webpack.config.js

Added support for `npm run local` which will watch and serve in one.

Add npm local script for watching and serving

---

README.md

Readme update for local engine builds

---

src/viewer.ts

Fix startup console error

---

package-lock.json
package.json

Update package in order to include latest engine changes.

Update package.json (for latest engine)

---

lib/download-texture.js
src/viewer.ts

This PR fixes some filtering issues on Safari.

Filtering fixes

---

package-lock.json
package.json
src/controls.tsx
src/index.tsx
src/viewer.ts

Fixes #68
This PR includes the following changes:
- add a slider for rotating the lighting environment
- disable alpha on render target to address incorrectly rendered glass
- update to pcui v1.0.8
- update 'local' npm script to pull in local engine
- add 'local:dbg' to pull in debug engine

Env rotation

---

src/style.css

Fixes https://github.com/playcanvas/playcanvas-viewer/issues/73

Make sliders stretch

---

package-lock.json
package.json
src/index.tsx
src/viewer.ts

Update the playcanvas dependancy to v1.38.0

---

src/style.css

Fixes https://github.com/playcanvas/playcanvas-viewer/issues/83

Center labels vertically

---

src/index.tsx
src/style.css
src/viewer.ts

Fixes https://github.com/playcanvas/playcanvas-viewer/issues/58
https://user-images.githubusercontent.com/850969/105493999-ca289480-5cc2-11eb-913e-8aad5f71759e.mov

Added spinner when files are being loaded

---

src/errors.tsx
src/index.tsx
src/style.css
src/viewer.ts

Fixes https://github.com/playcanvas/playcanvas-viewer/issues/53

Show error messages when a container fails to load

---

package-lock.json
package.json

Verifying PCUI 1.1.11 works great with the viewer. Spoiler alert: it does. 🚀 

Update PCUI to 1.1.11

---

lib/hdr-texture.js

Fixes https://forum.playcanvas.com/t/playcanvas-viewer-loading-with-large-hdr/18121

Fix HDR width test

---

package-lock.json
package.json
src/controls.tsx
src/index.tsx
src/style.css
src/types.ts
src/viewer.ts

Displays the hierarchy of the loaded glTF model in a new model panel and the total verts / primitives contained in that model. Each node in the hierarchy can also be selected to view their local transform.

Create a model hierarchy inspector

---

package.json
src/index.ejs
webpack.config.js

Fixes #
Google Analytics support for deployment on playcanvas.com/viewer.

google analytics for the viewer

---

src/controls.tsx

Ensure each morph target panel is given a unique key

---

src/controls.tsx
src/debug.ts
src/index.tsx
src/viewer.ts

This PR:
- makes debug skeleton axes a toggle
- fixes drag & drop on safari
- small fix for dragging non-animated models onto scene with already animating models

Bounds, drag & drop fix

---

src/debug.ts
static/asset_manifest.json

Bone axes were being incorrectly sized based on the bone transform scale.
This PR makes sure axes are sized according to bone lengths only.

Scale bone axes correctly

---

src/index.tsx

Vector inputs store their vectors in an object format. The initial data for them supplied by the Observer should be in the same format.

Update the vector input data in the main observer

---

rollup.config.js
src/index.mustache

Address issues with the moustache template.

Html template fix

---

package-lock.json
src/debug.ts
src/index.tsx
src/multiframe.ts
src/read-depth.ts
src/viewer.ts
static/scripts/orbit-camera.js

Partly addresses: https://github.com/playcanvas/engine/issues/3361
This PR:
- implements multiframe supersampled antialiasing (`multiframe.ts`) which works as follows:
- during camera movement the scene is rendered normally to offscreen render target
- once camera is determined to be stationary:
- further frames are rendered, but with a sub-pixel jittered projection matrix
- global texture bias is set to match #samples
- the additional frames are accumulated into a floating buffer
- once the total number of frames have been accumulated, the result is shown to the user
- i.e. the high quality 'pops in' once the camera stops moving, after a short delay
- uses the device max anisotropy on all textures
- adds the ability to double click the scene to set the orbit camera focus point …

Add multiframe supersampling

---

src/viewer.ts

Updates the viewer to make use of the anim component's scripting API.

AnimComponent API update

---

src/controls.tsx
src/index.tsx
src/viewer.ts

This PR removes the previous environment "intensity" control and replaces it with a much more natural "exposure" slider.

Expose environment exposure

---

src/viewer.ts

Camera's render target wasn't using maxPixelRatio. Thanks to @yaustar for finding this issue.

Take into consideration max-pixel-ratio

---

src/controls.tsx
src/index.tsx
src/multiframe.ts
src/style.css
src/viewer.ts

This PR adds 'Render' controls, to allow user to toggle multisampling, high quality rendering and to scale pixels:
In addition, styling is updated to space controls consistently.

Add render settings

---

src/controls.tsx
src/index.tsx
src/viewer.ts

Add support for variant selection.
https://user-images.githubusercontent.com/107400752/185088949-eb3efbf8-f0ef-48ae-abc2-5090062b33dd.mp4
Also enable grab pass in the viewer so we can support dynamic refractions.
https://user-images.githubusercontent.com/107400752/185089548-4a47a0c7-9739-47ac-b478-e639f076c0db.mp4

Variant picking and dynamic refractions

---

src/viewer.ts

This PR updates the handling of material variants.
All variants from all loaded models are now available to be selected.

Handle variants

---

package-lock.json
package.json
rollup.config.js
src/index.tsx
src/material.ts
src/multiframe.ts
src/style.css
src/types.ts
src/ui/left-panel/index.tsx
src/ui/popup-panel/index.tsx
src/viewer.ts

This PR:
- adds simple support for viewing the currently loaded model in WebXR AR
- fixes a bug which resulted in viewer not working on mobile

Add webxr preview

---

package-lock.json
package.json
src/ui/components/index.tsx

Includes typed PCUI react components

PCUI v2.8.0

---

package-lock.json
package.json
src/ui/components/index.tsx
tsconfig.json

Update the version of PCUI used by the model viewer to 2.9.1

PCUI version update

---

package-lock.json
package.json
rollup.config.mjs
tsconfig.json

PCUI v3.0.0

---

package-lock.json
package.json
src/ui/components/index.tsx

Update the model viewer to use PCUI version 4.0.0

---

package-lock.json
package.json
rollup.config.mjs
src/index.tsx
tsconfig.json

This PR prints the package versions of the model-viewer, pcui and engine to the console at startup.

Print package versions to console

---

package-lock.json
package.json
src/index.tsx
src/viewer.ts

Store shadowCatcher settings

---

package.json

Update lint command. Path src/lib does not exist under src.

chore: update lint command

---

src/ui/left-panel/index.tsx
src/viewer.ts

Fixes for latest version of model-viewer:
- drag and drop anyone on screen
- viewport dimensions update correctly

Fix drag & drop and viewport ui update

---

package-lock.json
package.json

Update model-viewer to include fixes in [engine v1.66.1](https://github.com/playcanvas/engine/releases/tag/v1.66.1)

Update to latest engine

---

package-lock.json
package.json
src/splat-resource.ts

Send data back to worker immediately upon upload.

Small update

---

src/splat-resource.ts

Additional components will be moved to a texture in a separate PR. The color will be also removed from VB in a separate PR.

Splatting uses colors stored in a texture instead of vertex buffer

---

src/splat/ply-parser.ts
src/splat/splat-data.ts
src/splat/splat-material.ts
src/splat/splat-resource.ts
src/splat/splat.ts

This PR:
- split the source splat data into a handler class
- split out splat material

Extract splat data

---

src/splat/splat-material.ts
src/splat/splat.ts

- also unified normal & debug shaders using ifdef

Splat scale is stored in texture instead of VB

---

src/splat/splat-resource.ts

Fix for splat loading

---

src/splat/splat-resource.ts
src/splat/splat.ts

This PR updates the `Splat` class to allow updates to the data:
- constructor creates the required resources based on number of splats
- expose functions for updating the splat data

Support splat update

---

src/splat/sort-manager.ts
src/splat/splat-data.ts
src/splat/splat-material.ts
src/splat/splat-resource.ts
src/splat/splat.ts
src/viewer.ts

This PR:
- add the ability to attach a new `SplatData` property, mainly for splat data edit support
- `SplatResource` stores instance information
- add destroy functions to splat and data

Store splat instances, support adding splat property

---

package-lock.json
package.json
src/debug-lines.ts
src/viewer.ts

This PR makes the following changes:
- remove legacy skybox loading code
- colour the bone axes correctly (XYZ axes were being colored GBR instead of RGB).
- specify filter to PLY loader so compressed PLY files load correctly

Various fixes

---

src/ui/components/index.tsx
src/ui/errors.tsx
src/ui/index.tsx
src/ui/left-panel/index.tsx
src/ui/left-panel/morph-target-panel.tsx
src/ui/load-controls.tsx
src/ui/popup-panel/animation-controls.tsx
src/ui/popup-panel/index.tsx
src/ui/popup-panel/panels.tsx
src/ui/selected-node.tsx
tsconfig.json

Reverts playcanvas/model-viewer#274

Revert "Set import paths correctly for PCUI React"

---

src/shadow-catcher.ts

Fix CameraComponent type

---

package-lock.json
package.json
src/index.tsx
src/types.ts
src/viewer.ts

This PR stops model-viewer centering objects by default and updates package dependencies.

Refrain from centering objects by default

---

src/orbit-camera.ts
src/viewer.ts

Fix initial camera position and handle center scene in XR mode.

More camera fixes

---

src/xr-mode.ts

- Modified private `_viewInvMatrix` property to use inverted viewMatrix from camera

ViewInvMatrix reference fix

---

src/ui/load-controls.tsx

Make it clear to the user that .glb, .gltf and .ply files are supported:
Also filter the file open dialog:

Message to user which file types are supported

---

eslint.config.mjs
package-lock.json
package.json
src/debug-lines.ts
src/drop-handler.ts
src/index.tsx
src/multiframe.ts
src/png-exporter.ts
src/read-depth.ts
src/shadow-catcher.ts
src/ui/components/index.tsx
src/ui/errors.tsx
src/ui/index.tsx
src/ui/left-panel/index.tsx
src/ui/left-panel/morph-target-panel.tsx
src/ui/load-controls.tsx
src/ui/popup-panel/animation-controls.tsx
src/ui/popup-panel/index.tsx
src/ui/popup-panel/panels.tsx
src/ui/selected-node.tsx
src/viewer.ts
src/xr-mode.ts

This PR includes bumping ESLint to latest and moves to the latest PlayCanvas ESLint config.

Update NPM dependencies

---

rollup.config.mjs

Specify a reserved class name to terser, see https://github.com/playcanvas/engine/issues/7580.

Fix release build

---

src/shadow-catcher.ts
src/viewer.ts

This PR updates the shadow catcher to work correctly in AR mode.

Fix shadow catcher

---

src/viewer.ts

- Adjusted fly speed multiplier based on scene size

Fly speed multiplier fix

---

src/camera-controls.ts
src/style.scss

- Removed slow rotate and move speed mobile
- Moved AR button to bottom left to free fullscreen button

Mobile fixes

---

.github/workflows/ci.yml
README.md
eslint.config.mjs
package.json
rollup.config.mjs

- Updated README
- Updated package json and workflows to match template repo

Structure fixes
